name: Java CI with Maven on ubuntu-latest

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/.github/workflows/**'
      - '**/LICENSE'
      
  pull_request:
      paths-ignore:
      - '**/README.md'
      - '**/.github/workflows/**'
      - '**/LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     workdir: raffaelliscandiffio.shop-totem

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
         ~/.m2
         ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Run test 
      id: mvnTest
      run: xvfb-run mvn test
      working-directory: ${{ env.workdir }}
              
    - name: Run mutation test on pull_request
      id: pitest
      run: mvn org.pitest:pitest-maven:mutationCoverage
      if: ${{ always() && github.event_name == 'pull_request' && steps.mvnTest.outcome == 'success' }}
      working-directory: ${{ env.workdir }}

    - name: Build with Maven, analysed with SonarCloud
      run: >
       xvfb-run mvn verify
       org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
       -Dsonar.organization=francescoscandiffio-github
       -Dsonar.host.url=https://sonarcloud.io
       -Dsonar.projectKey=FrancescoScandiffio_shop-totem
      working-directory: ${{ env.workdir }}
      env: 
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

    - name: Generate JUnit Report
      run: mvn surefire-report:report-only site:site -DgenerateReports=false
      if: ${{ always() && (steps.mvnTest.outcome == 'failure') }}
      working-directory: ${{ env.workdir }}

    - name: Archive JUnit Report
      uses: actions/upload-artifact@v2
      if: ${{ always() && (steps.mvnTest.outcome == 'failure') }}
      with:
        name: surefire-report-jdk-11
        path: '**/target/site'
        
    - name: Archive Pitest Report
      uses: actions/upload-artifact@v2
      if: ${{ always() && (steps.pitest.outcome == 'failure') }}
      with:
        name: pitest-report-jdk-11
        path: '**/target/pit-reports'