name: Java CI with Maven on windows and macos

on:
  pull_request:
      paths-ignore:
      - '**/README.md'
      - '**/.github/workflows/**'
      - '**/LICENSE'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
     workdir: raffaelliscandiffio.shop-totem
    strategy:
      matrix:
        os: [macos-11, windows-2022]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Build with Maven
      run: mvn verify
      working-directory: ${{ env.workdir }}

    - name: Generate JUnit Report
      run: mvn surefire-report:report-only site:site -DgenerateReports=false
      if: ${{ failure() }}
      working-directory: ${{ env.workdir }}

    - name: Archive JUnit Report
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: surefire-report-jdk-8
        path: '**/target/site'
     