name: Java CI with Maven on MacOS

on:
  pull_request:
      paths-ignore:
      - '**/README.md'
      - '**/.github/workflows/**'
      - '**/LICENSE'

jobs:
  build:
    runs-on: macos-11
    env:
     workdir: raffaelliscandiffio.shop-totem

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Build with Maven
      run: mvn verify -DskipBDDs=true
      working-directory: ${{ env.workdir }}

    - name: Generate JUnit Report
      run: mvn surefire-report:report-only site:site -DgenerateReports=false
      if: ${{ failure() }}
      working-directory: ${{ env.workdir }}

    - name: Archive JUnit Report
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: surefire-report-jdk-8
        path: '**/target/site'
     